Delete spawned model when rospy shutdown
ros-simulation/gazebo_ros_pkgs pull request #480
Opened 2016-08-05 10:06 UTC by laurent-george

Usefull when spawn model script is used in a launch file. Each time the
launch is stoped (i.e ctrl-c) the spawned model is removed from gazebo.
It allows to relaunch multiple time the same launch file which occurs
frequently when updating urdf model.

2016-09-14 23:50 UTC, j-rivero commented
Hello Laurent, thanks for the PR. Let me fully understand which is the problem, could you please describe which is the use case that this PR will fix? Or in other words, what are you trying to do that you can not do without this PR.

Thanks!

2016-09-15 09:10 UTC, laurent-george commented
Sorry I send the pull request in a hurry and didn't explain the use case.

During development of a new robot, I follow an iterative approach to configure the robot URDF file for simulation. It consists mainly in setting some gazebo parameters in the URDF (e.g. configuring frictions, max effort etc) and testing if the simulation seems correct.  I usually modify the URDF, stop simulation, start it again and re-spawn the robot in gazebo. This work-flow is a bit heavy.

One way to reduced this work-flow, is to keep the same gazebo simulation running and only "removing" the robot before re-spawning it with the new URDF parameters.

My first try was to manually remove the robot using: `rosservice call /gazebo/delete_model "model_name: "'my_robot_name'"`. But as I usually use a launch file to spawn the robot in gazebo, a more automatic way seems possible: the spawned robot model could be removed if the launch file receive a SIGINT  (e.g with a ctrl-c). 

Thus, my second try was to make the spawn_model node to stay active in background until a SIGINT is received, and if a SIGINT is received remove the robot model automatically. That is the purpose of this pull request. The workflow is less heavy and becomes:

```
launch gazebo
while (not(is_simulation_ok())):
    edit the robot urdf
    launch roslaunch file to spawn the robot # this send a ctrl-c to previously launch node)
```

The launch file that I use is like this:

    <param name="robot_description" command="$(find xacro)/xacro.py '$(find stan_description)/urdf/stan_v2.xacro' --inorder in_simulation:=true" />
    <node name="mybot_spawn" pkg="gazebo_ros" type="spawn_model" args="-urdf -param robot_description -model my_robot_name -z 0.0001 -x 37.90 -y 27.26 -Y -0.075" />
    <node .. others nodes ... />

2018-05-25 17:52 UTC, kev-the-dev requested changes
Thanks for the contribution! This changes the default behavior of the script and would be disruptive to current users. I think this would be more appropriate for a new script, perhaps ```delete_model```, which could have a flag ```-on-exit``` to have this delete when shutdown behavior.

2018-05-25 18:30 UTC, ironmig commented
Actually this was implemented in #435 (this is a duplicate). @scpeters can we close this?

2018-05-28 07:40 UTC, closed without merging