Implemented APIs to simulate torque control.
ros-simulation/gazebo_ros_pkgs pull request #563
Opened 2017-04-13 08:03 UTC by daichi-yoshikawa

I wanted a straight way to do simulation of torque control for mobile manipulator.
In order to do so, I added APIs as the follow.

With the APIs, user can do torque simulation as the follow.
1. By using ROS service "AddJoint", register joints which you'd like to use for torque control.
2. Setup shared memory to share desired torques with gazebo simulator.
3. Send desired torques to gazebo simulator via the above shared memory
4. Gazebo simulator checks shared memory in very short interval(Default: 1ms)
5. If the desired torques are for joints registered in advance, simulator applies the torques to each joint and simulates the behavior.

To realize the above, I did the follows.
- Implemented SharedMemory class in gazebo namespace, which is used to deliver desired torques to gazebo simulator. 
- Added ROS services like AddJoint, to inform gazebo_ros joint which is used for torque control
- Added reception of desired torque to gazebo_ros_api_plugin.cpp
- Added part applying desired torque to proper joint.

Thank you.

2017-04-15 20:09 UTC, davetcoleman requested changes

2017-04-15 20:09 UTC, davetcoleman commented on gazebo_msgs/msg/JointStates.msg
> +float64[] dq                    # velocity of q
this message is a duplicate of the standard [JointState](http://docs.ros.org/kinetic/api/sensor_msgs/html/msg/JointState.html)

2017-04-15 20:09 UTC, davetcoleman commented on gazebo_msgs/srv/AddJoint.srv
> +float64 effort_time
comment to explain what effort time is?

2017-04-15 20:09 UTC, davetcoleman commented on gazebo_msgs/srv/AddForceSensor.srv
> +string joint_name
Add comment to explain where the sensor is added for the joint? Same for the torque sensor service

2017-04-15 20:09 UTC, davetcoleman commented on gazebo_msgs/srv/StartTimer.srv
> +float64 duration_write_joint_states
comment documentation? also, this service seems a little too application-specific

2017-04-15 20:09 UTC, davetcoleman commented on gazebo_ros/include/gazebo_ros/gazebo_ros_api_plugin.h
>    /// \brief
fill in comments for functions, please

2017-04-15 20:09 UTC, davetcoleman commented on gazebo_ros/include/gazebo_ros/gazebo_ros_api_plugin.h
> +  /// \brief Daichi
Daichi?

2017-04-15 20:09 UTC, davetcoleman commented on gazebo_ros/include/gazebo_ros/shared_memory.h
> +/*********************************************************************
should be apache license to match this repo

2017-04-15 20:09 UTC, davetcoleman commented on gazebo_ros/include/gazebo_ros/shared_memory.h
> +class SharedMemory
Why is this class necessary? Does C++11 provide this functionality?

2017-04-15 20:16 UTC, davetcoleman commented
Before you address my code review, I actually think we need to discuss whether the overall approach here is the right one for interfacing ROS controllers with Gazebo. A project I worked on for Gazebo many years ago was ROS-Control integration with Gazebo, and it supports torque control as well. Using that would be an [alternative approach](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/kinetic-devel/gazebo_ros_control/src/default_robot_hw_sim.cpp#L249) that I recommend, though most of its testing has been done with position and velocity control, so you might need to add more code for torque control.

Another approach would be to wrap all this functionality you've added to the Gazebo-ROS-API-Plugin into a separate plugin so that using it is optional - currently everyone using Gazebo+ROS will have all these topics and services advertised even if they are just controlling a diff-drive mobile base, etc.

2022-11-22 11:54 UTC, ahcorde commented
targeting an [unsupported version](http://wiki.ros.org/Distributions). Closing this feel free to reopen again in a supported version if the PR is still relevant.

2022-11-22 11:54 UTC, closed without merging