add option to input xml from stdin to spawn_model
ros-simulation/gazebo_ros_pkgs pull request #603
Opened 2017-07-27 20:55 UTC by sputnick1124

This allows for on-the-fly model description (e.g. with `sed`, `xacro.py`, `erb`) without the need to store a model in the database for each. Useful for some swarming applications if plugins need different parameters for each instance of the robot.

Example usage:
`rosun gazebo_ros spawn_model -sdf -stdin "$(cat model.sdf | sed 's/arg/newarg/g')" -model modified_robot`

2018-04-05 22:16 UTC, j-rivero commented
@osrf-jenkins run tests please

2018-05-25 17:05 UTC, kev-the-dev requested changes
I like this idea! However, I think the argument "stdin" is misleading. This seems to actually just read the model_xml from the program arguments. I think a better style is to use ```sys.stdin```, so the usage would be like
 ```cat model.sdf | sed 's/arg/newarg/g' | rosun gazebo_ros spawn_model -sdf -stdin -model modified_robot```

2018-05-30 02:39 UTC, sputnick1124 commented
Great points, @ironmig! I'll make some changes to the interface to make it more pipe-friendly. I agree that calling it stdin is a bit misleading. I think I originally was going for exactly what you described, but got sidetracked halfway through testing the proof of concept.

2018-06-04 23:30 UTC, ironmig commented
Thanks for the updates. I'll be integrating this into my refactor of the script in #730 so it may be merged there instead of here.

2018-07-06 00:06 UTC, ironmig commented
Merged into PR 730, thanks for the idea and code contribution!

2018-07-06 00:06 UTC, closed without merging