Support 16-bit cameras
ros-simulation/gazebo_ros_pkgs pull request #675
Opened 2018-02-15 23:57 UTC by scpeters

Adds support for 16-bit cameras, along with a test. Code is from @iche033; I added the test.

2018-02-23 10:14 UTC, scpeters commented
the test doesn't get run by CI, so a reviewer should run it manually with `-DENABLE_DISPLAY_TESTS=True`

2018-03-01 23:46 UTC, iche033 requested changes

2018-03-01 23:46 UTC, iche033 commented on gazebo_plugins/src/gazebo_ros_camera_utils.cpp
> +    unsigned int step = this->skip_* this->width_ *
I wasn't quite sure what `skip_` represents. I assumed it's the number of channels so put down 1 for `MONO16` and 3 for `RGB16` above. But thinking about it more, it believe it should be the number of bytes per pixel. So it'll be 2 for `MONO16` and 6 for `RGB16`. In this case, `step` would just be `this->skip_*this->width_` (ie. you can keep the old code before the changes here)

2018-03-01 23:46 UTC, iche033 commented on gazebo_plugins/src/gazebo_ros_camera_utils.cpp
> +    unsigned int step = this->skip_* this->width_ *
actually I made these changes. I'll update them now

2018-03-01 23:46 UTC, iche033 commented on gazebo_plugins/src/gazebo_ros_camera_utils.cpp
> +    unsigned int step = this->skip_* this->width_ *
just realized the PR is created from a branch in your repo. Could you apply the following patch? thanks

~~~
diff --git a/gazebo_plugins/src/gazebo_ros_camera_utils.cpp b/gazebo_plugins/src/gazebo_ros_camera_utils.cpp
index d527fb6..c4c7da3 100644
--- a/gazebo_plugins/src/gazebo_ros_camera_utils.cpp
+++ b/gazebo_plugins/src/gazebo_ros_camera_utils.cpp
@@ -414,7 +414,7 @@ void GazeboRosCameraUtils::Init()
   else if (this->format_ == "L16" || this->format_ == "L_INT16")
   {
     this->type_ = sensor_msgs::image_encodings::MONO16;
-    this->skip_ = 1;
+    this->skip_ = 2;
   }
   else if (this->format_ == "R8G8B8" || this->format_ == "RGB_INT8")
   {
@@ -429,7 +429,7 @@ void GazeboRosCameraUtils::Init()
   else if (this->format_ == "R16G16B16" ||  this->format_ == "RGB_INT16")
   {
     this->type_ = sensor_msgs::image_encodings::RGB16;
-    this->skip_ = 3;
+    this->skip_ = 6;
   }
   else if (this->format_ == "BAYER_RGGB8")
   {
@@ -594,11 +594,9 @@ void GazeboRosCameraUtils::PutCameraData(const unsigned char *_src)
     this->image_msg_.header.stamp.sec = this->sensor_update_time_.sec;
     this->image_msg_.header.stamp.nsec = this->sensor_update_time_.nsec;
 
-    unsigned int step = this->skip_* this->width_ *
-        sensor_msgs::image_encodings::bitDepth(this->type_)/8;
     // copy from src to image_msg_
     fillImage(this->image_msg_, this->type_, this->height_, this->width_,
-        step, reinterpret_cast<const void*>(_src));
+        this->skip_*this->width_, reinterpret_cast<const void*>(_src));
~~~

2018-03-01 23:50 UTC, iche033 approved these changes

2018-03-02 00:23 UTC, scpeters commented
There's an issue with the test: I made a distinct rostest file, but am re-using the camera.cpp file. This allows separate tests to be run, but camera.cpp file now makes two copies of the test results file. I might need to fork camera.cpp into camera16.cpp

2018-03-02 00:37 UTC, scpeters commented
I've refactored the camera test in 389c550, with the implementation in camera.h and a distinct test name in camera16bit.cpp

2018-03-04 23:50 UTC, j-rivero commented
@osrf-jenkins run tests please

2018-03-05 12:11 UTC, j-rivero commented
One of the tests (DistortionTest.cameraDistortionTest) is failing, but is not related to this PR. The merge of https://bitbucket.org/osrf/release-tools/pull-requests/375/enable-display-test-in-gazebo_ros_pkgs triggered this error.

2018-03-05 17:06 UTC, scpeters commented
The distortion test fails on my desktop too. I've been trying to figure out the problem

2018-03-15 23:17 UTC, scpeters commented
I just rebased on kinetic to get the renamed distortion tests

2018-04-05 21:57 UTC, merged