[ros2] Port tricycle_drive plugin to ros2
ros-simulation/gazebo_ros_pkgs pull request #917
Opened 2019-04-06 19:48 UTC by shiveshkhaitan

Port gazebo_ros_tricycle_drive plugin to ROS2. 

Example:
```
<plugin name='tricycle_drive' filename='libgazebo_ros_tricycle_drive.so'>
  <ros>
    <namespace>/demo</namespace>
    <argument>cmd_vel:=cmd_demo</argument>
    <argument>odom:=odom_demo</argument>
  </ros>

  
  <steering_joint>wheel_front_steer</steering_joint>
  <actuated_wheel_joint>wheel_front_spin</actuated_wheel_joint>
  <encoder_wheel_left_joint>wheel_rear_left_spin</encoder_wheel_left_joint>
  <encoder_wheel_right_joint>wheel_rear_right_spin</encoder_wheel_right_joint>

  
  <wheel_separation>1.0</wheel_separation>
  <encoder_wheel_diameter>0.3</encoder_wheel_diameter>
  <actuated_wheel_diameter>0.3</actuated_wheel_diameter>

  
  <max_wheel_torque>20</max_wheel_torque>
  <max_wheel_acceleration>5.0</max_wheel_acceleration>
  <max_steering_speed>1.0</max_steering_speed>

  
  <publish_odom>true</publish_odom>
  <publish_wheel_tf>true</publish_wheel_tf>
  <publish_wheel_joint_state>true</publish_wheel_joint_state>

  <odometry_frame>odom_demo</odometry_frame>
  <robot_base_frame>fork</robot_base_frame>

</plugin>
```

2019-05-17 17:47 UTC, chapulina commented
Attempt at running CI: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=7136)](https://ci.ros2.org/job/ci_linux/7136/)

2019-05-18 14:08 UTC, shiveshkhaitan commented
Probably the test failed because of the required angular velocity set in the test which is not feasible given the current constraints of the model. (Not sure how the test passed initially)

2019-05-19 17:42 UTC, chapulina commented
It could also be something else, note that the diff drive test is also failing on this branch (along with many others)

2019-05-19 19:22 UTC, shiveshkhaitan commented
I tried building ros-simulation/gazebo_ros_pkgs branch ros2 and crystal. The tests for diff_drive, force, imu_sensor and joint_state_publisher failed there too. Can it be not because of tricycle_drive and something else?

2019-05-22 01:41 UTC, chapulina commented
@shiveshkhaitan , #926 fixed all tests and warnings on the `ros2` branch. Once you rebase this PR I can trigger new CI.

2019-05-22 08:16 UTC, shiveshkhaitan commented
The tests seem to pass successfully on my system. What could be the problem?

2019-05-28 19:06 UTC, chapulina requested changes
This is looking great! Mind adding a migration guide to the wiki?

I have several minor comments, most of which have been carried from the ROS 1 implementation. So not really this PR's fault, but this is a good chance to address them nonetheless.

All tests pass locally for me. I only see a couple of deprecation warnings coming from the video plugin, but the tricycle is clean. We should make a new PR to clean up the video warnings. Once you address my comments I can trigger new CI.

2019-05-28 19:06 UTC, chapulina commented on gazebo_plugins/src/gazebo_ros_tricycle_drive.cpp
> +void GazeboRosTricycleDrive::Reset() {}
Were you planning on doing something here? Right now, when the world is reset (`Ctrl+R`), the vehicle seems to lose its angular velocity and starts to respond weirdly to commands.

2019-05-28 19:06 UTC, chapulina commented on gazebo_plugins/src/gazebo_ros_tricycle_drive.cpp
> +#include <nav_msgs/msg/occupancy_grid.hpp>
I don't see `occupancy_grid` being used anywhere

2019-05-28 19:06 UTC, chapulina commented on gazebo_plugins/src/gazebo_ros_tricycle_drive.cpp
> +#include <assert.h>
Do you need this header?

2019-05-28 19:06 UTC, chapulina commented on gazebo_plugins/src/gazebo_ros_tricycle_drive.cpp
> +    double target_wheel_roation_speed = cmd_.linear.x / ( actuated_wheel_diameter / 2.0 );
Should we also lock the mutex here where we use `cmd_`?

2019-05-28 19:06 UTC, chapulina commented on gazebo_plugins/src/gazebo_ros_tricycle_drive.cpp
> +  const gazebo::common::Time & current_time = _current_time;
Is this copy necessary?

2019-05-28 19:06 UTC, chapulina commented on gazebo_plugins/src/gazebo_ros_tricycle_drive.cpp
> +  // Book: Sigwart 2011 Autonompus Mobile Robots page:337
oops, the typo was already there, but I think this is `Autonomous`

2019-05-28 19:06 UTC, chapulina commented on gazebo_plugins/src/gazebo_ros_tricycle_drive.cpp
> +  odom_.pose.pose.orientation.w = qt.w();
Suggestion: use [tf2_geometry_msgs](http://wiki.ros.org/tf2_geometry_msgs) to do the conversion here. It's a trivial conversion, but it often helps preventing typos.

2019-05-28 19:06 UTC, chapulina commented on gazebo_plugins/src/gazebo_ros_tricycle_drive.cpp
> +  double max_wheel_torque_;
This is only used in the `Load` function, so it doesn't need to be kept in a member variable

2019-05-28 19:06 UTC, chapulina commented on gazebo_plugins/src/gazebo_ros_tricycle_drive.cpp
> +  // Get joints
If the joint asked by the user is not found, these joints will be `nullptr`. We should check every joint and if any is null, print an error and fail to initialize the plugin.

2019-05-28 19:06 UTC, chapulina commented on gazebo_plugins/src/gazebo_ros_tricycle_drive.cpp
> +  std::vector<gazebo::physics::JointPtr> joints;
This vector will be the same at every iteration. How do you feel about populating it once at `Load` and keeping it as a member variable? It can be used both at `PublishWheelJointState` and `PublishWheelsTf`.

2019-05-28 19:06 UTC, chapulina commented on gazebo_plugins/src/gazebo_ros_tricycle_drive.cpp
> +    tf2::Vector3 vt(pose.Pos().X(), pose.Pos().Y(), pose.Pos().Z());
I suggest you add a couple of conversion functions for these types to `gazebo_ros/conversions`. Not a requirement, just something nice to have. Especially when dealing with quaternions, it saves people time looking up if the order is XYZW or WXYZ.

2019-05-28 19:06 UTC, chapulina commented on gazebo_plugins/src/gazebo_ros_tricycle_drive.cpp
> +  if (seconds_since_last_update > update_period_) {
A nitpick of mine is to always return as early as possible to make the code less indented and more readable. So I'd recommend doing:

```
if (seconds_since_last_update < update_period_)
  return;
```

Also I believe we want to update if `seconds_since_last_update == update_period_`. So if you keep your logic, I think you may need to change to `>=`.

2019-05-28 19:06 UTC, chapulina commented on gazebo_plugins/src/gazebo_ros_tricycle_drive.cpp
> +  if (max_wheel_accel_ > 0) {
Should we also check `max_wheel_decel` here and on line 430?

2019-05-28 19:06 UTC, chapulina commented on gazebo_plugins/src/gazebo_ros_tricycle_drive.cpp
> +    if (target_angle < -M_PI / 2.0) {
This `else` and `if` can be combined into an `else if`

2019-05-29 14:17 UTC, shiveshkhaitan commented on gazebo_plugins/src/gazebo_ros_tricycle_drive.cpp
> +void GazeboRosTricycleDrive::Reset() {}
Can you please suggest what should be the appropriate behaviour when gazebo is reset for tricycle drive?

2019-05-29 14:20 UTC, shiveshkhaitan commented on gazebo_plugins/src/gazebo_ros_tricycle_drive.cpp
> +    tf2::Vector3 vt(pose.Pos().X(), pose.Pos().Y(), pose.Pos().Z());
I realised that `qt` and `vt` here were not being used. Nevertheless I will be adding the required conversions in `gazebo_ros`.

2019-05-29 15:53 UTC, chapulina commented on gazebo_plugins/src/gazebo_ros_tricycle_drive.cpp
> +void GazeboRosTricycleDrive::Reset() {}
I'd expect the vehicle to go back to the initial position and be stopped. So all the plugin should need to do is zero the velocity commands.

2019-05-29 15:54 UTC, chapulina commented on gazebo_plugins/src/gazebo_ros_tricycle_drive.cpp
> +    tf2::Vector3 vt(pose.Pos().X(), pose.Pos().Y(), pose.Pos().Z());
Oh nice catch, feel free to add that in a separate PR then, no need to block this one on this :wink:

2019-05-29 17:16 UTC, shiveshkhaitan commented on gazebo_plugins/src/gazebo_ros_tricycle_drive.cpp
> +  double max_wheel_torque_;
This is reintroduced in the latest commit as its required in reset function as well

2019-05-29 18:35 UTC, shiveshkhaitan commented
Migration guide is available at [ROS 2 Migration: Tricycle drive](https://github.com/ros-simulation/gazebo_ros_pkgs/wiki/ROS-2-Migration:-Tricycle-drive)

2019-05-29 20:58 UTC, chapulina approved these changes
Looks great! Merging!

2019-05-29 20:58 UTC, merged