[ros2] Port F3d plugin to ros2
ros-simulation/gazebo_ros_pkgs pull request #921
Opened 2019-05-06 02:14 UTC by shiveshkhaitan

Port gazebo_ros_f3d plugin to ROS2.

Example:

```
<plugin name="gazebo_ros_f3d" filename="libgazebo_ros_f3d.so">
    <ros>
        
        <namespace>/demo</namespace>
        
        <argument>wrench:=wrench_demo</argument>
    </ros>

    
    <body_name>link</body_name>
    
    
    <frame_name>demo_world</frame_name>

</plugin>
```

2019-05-27 17:17 UTC, shiveshkhaitan commented
Merged similar plugins gazebo_ros_f3d and gazebo_ros_ft_sensor into gazebo_ros_ft_sensor for ROS2.

Example:

```
<plugin name="gazebo_ros_ft_sensor" filename="libgazebo_ros_ft_sensor.so">
    <ros>
        <!-- Add a namespace -->
        <namespace>/demo</namespace>
        <!-- Remap the default topic -->
        <argument>wrench:=wrench_demo</argument>
    </ros>

    <!-- Link name -->
    <body_name>link</body_name>
    
    <!-- Frame id of published message -->
    <frame_name>demo_world</frame_name>
    
    <!-- Update rate in Hz, defaults to 0.0, which means as fast as possible -->
    <update_rate>1</update_rate>

    <!-- Standard deviation of the noise to be added to the reported wrench messages. -->
    <gaussian_noise>0.01</gaussian_noise>
</plugin>
```
If `<body_name>` is specified, it acts as original f3d_plugin. Otherwise if `<joint_name>` is specified, it acts as original ft_sensor

2019-06-04 06:17 UTC, shiveshkhaitan commented
Migration guides are available at [ROS 2 Migration: FT sensor](https://github.com/ros-simulation/gazebo_ros_pkgs/wiki/ROS-2-Migration:-FT-sensor) and [ROS 2 Migration: F3D](https://github.com/ros-simulation/gazebo_ros_pkgs/wiki/ROS-2-Migration:-F3D)

2019-06-07 17:20 UTC, chapulina requested changes
Thank you for the migration guides, this works for me!

I just have a few minor comments. Also, don't forget to delete `gazebo_ros_ft_sensor` from `.ros1_unported`

2019-06-07 17:20 UTC, chapulina commented on gazebo_plugins/src/gazebo_ros_ft_sensor.cpp
> +#include <gazebo/physics/physics.hh>
Nitpick: instead of including all Gazebo physics, you could include exactly the headers you'll need, such as `Joint.hh`, `Link.hh`, etc.

2019-06-07 17:20 UTC, chapulina commented on gazebo_plugins/src/gazebo_ros_ft_sensor.cpp
> +    RCLCPP_WARN(impl_->rosnode_->get_logger(),
This should be an error instead of a warning, because the plugin will not work. And we should reset the node too so we don't have an extra node that's not being used.

The same goes for all the other checks that return in this function.

2019-06-07 17:20 UTC, chapulina commented on gazebo_plugins/src/gazebo_ros_ft_sensor.cpp
> +    auto link_name = _sdf->Get<std::string>("body_name", "link").first;
Since you already know that the element is present, you don't need to use the `Get` call that takes a default value, and could use this one instead: `auto link_name = _sdf->Get<std::string>("body_name");`

2019-06-07 17:20 UTC, chapulina commented on gazebo_plugins/include/gazebo_plugins/gazebo_ros_ft_sensor.hpp
> +      <!-- Frame id of published message -->
This can only be used in conjunction with `body_name`, right? If that's correct, mind documenting this here?

2019-06-07 17:20 UTC, chapulina commented on gazebo_plugins/test/test_gazebo_ros_ft_sensor.cpp
> +// Copyright 2018 Open Source Robotics Foundation, Inc.
2019 :wink:

2019-06-07 17:20 UTC, chapulina commented on gazebo_plugins/test/test_gazebo_ros_ft_sensor.cpp
> +  EXPECT_EQ("test_world", latest_msg->header.frame_id);
How about removing the ground plane on the world so the box free-falls, and we can check that we're correctly getting forces due to gravity? Something like this:

```.cpp
  EXPECT_DOUBLE_EQ(0.0, latest_msg.wrench.force.x);
  EXPECT_DOUBLE_EQ(0.0, latest_msg.wrench.force.y);
  EXPECT_DOUBLE_EQ(-9.8, latest_msg.wrench.force.z);
  EXPECT_DOUBLE_EQ(0.0, latest_msg.wrench.torque.x);
  EXPECT_DOUBLE_EQ(0.0, latest_msg.wrench.torque.y);
  EXPECT_DOUBLE_EQ(0.0, latest_msg.wrench.torque.z);
```

2019-06-18 12:33 UTC, chapulina approved these changes

2019-06-18 12:33 UTC, merged